### ISSUE TITLE
Add support for hex and base64 strings

### ISSUE THREAD

**Issue by mizvyt** [mizvyt/rfc1751.js#1]
Should include a utility for conversion to Uint8Array from hexadecimal and base64 encoded strings, and support union type `Uint8Array | number[] | string`.

**Comment by vmizg** [comment]
After some thought, I think it is better to keep this functionality outside of this library.
You can refer to https://cryptojs.gitbook.io/docs/#encoders to get a `Uint8Array` from your data.
